apiVersion: v1
kind: Service
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cms-api