apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  replicas: {{ .Values.cms_api.replicaCount }}
  selector:
    matchLabels:
      app: cms-api
  template:
    metadata:
      labels:
        app: cms-api
    spec:
      imagePullSecrets:
        - name: wowzaprivate
      containers:
        - name: cms-api
          image: "{{ .Values.cms_api.image.repository }}:{{  required "Must Supply .Values.cms_api.image.tag" .Values.cms_api.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.cms_api.resources | indent 12 }}
